project:
  type: website

website:
  title: "AnalyticsInAction.com"
  navbar:
    right:
      - icon: github
        href: https://github.com/ETC5523-2024/assignment-3-v2-creating-a-blog-Mhon0009
    left:
      - text: "About me"
        href: about.qmd
      - index.qmd
format:
  html:
    theme: Sketchy
    css: styles.css



